# Generated by Django 4.2.1 on 2023-06-01 08:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], max_length=10)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('birth_place', models.CharField(max_length=200)),
                ('living_place', models.CharField(max_length=200)),
                ('citizenship', models.CharField(max_length=200)),
                ('identity_document_name', models.CharField(max_length=100)),
                ('identity_document_ser', models.CharField(max_length=10)),
                ('identity_document_id', models.CharField(max_length=100)),
                ('identity_document_issued_info', models.CharField(max_length=400)),
                ('home_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('own_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('graduation_place', models.CharField(choices=[('School', 'Школа'), ('College', 'Колледж'), ('Lyceum', 'Лицей')], max_length=20)),
                ('graduation_certificate_ser', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)])),
                ('copy_passport', models.FileField(upload_to='')),
                ('copy_graduation_certificate', models.FileField(upload_to='')),
                ('image_three_to_four', models.FileField(upload_to='')),
                ('major_choice', models.CharField(choices=[('Technic', 'Техническое направление'), ('Economic', 'Экономическое направление')], max_length=200)),
                ('technic_major_choice_first', models.CharField(blank=True, choices=[('GI', 'Геофизические методы исследования скважин (ГИ) (специалитет)'), ('GC', 'Цифровой геоинжиниринг (ГЦ) (специалитет)'), ('RB', 'Бурение нефтяных и газовых скважин (РБ)'), ('OS', 'Эксплуатация и обслуживание объектов добычи нефти (РН)'), ('DG', 'Эксплуатация и обслуживание объектов добычи газа, газоконденсата и подземных хранилищ (РГ)'), ('TS', 'Сооружение и ремонт газонефтепроводов и газонефтехранилищ (ТС)'), ('TP', 'Эксплуатация и обслуживание объектов транспорта и хранения нефти, газа и продуктов переработки (ТП)'), ('RT', 'Технология бурения нефтяных и газовых скважин на суше и море (РТ) (специалитет)'), ('RS', 'Разработка и эксплуатация нефтяных и газовых месторождений (РС) (специалитет)')], max_length=200, null=True)),
                ('technic_major_choice_second', models.CharField(blank=True, choices=[('GI', 'Геофизические методы исследования скважин (ГИ) (специалитет)'), ('GC', 'Цифровой геоинжиниринг (ГЦ) (специалитет)'), ('RB', 'Бурение нефтяных и газовых скважин (РБ)'), ('OS', 'Эксплуатация и обслуживание объектов добычи нефти (РН)'), ('DG', 'Эксплуатация и обслуживание объектов добычи газа, газоконденсата и подземных хранилищ (РГ)'), ('TS', 'Сооружение и ремонт газонефтепроводов и газонефтехранилищ (ТС)'), ('TP', 'Эксплуатация и обслуживание объектов транспорта и хранения нефти, газа и продуктов переработки (ТП)'), ('RT', 'Технология бурения нефтяных и газовых скважин на суше и море (РТ) (специалитет)'), ('RS', 'Разработка и эксплуатация нефтяных и газовых месторождений (РС) (специалитет)')], max_length=200, null=True)),
                ('technic_major_choice_third', models.CharField(blank=True, choices=[('GI', 'Геофизические методы исследования скважин (ГИ) (специалитет)'), ('GC', 'Цифровой геоинжиниринг (ГЦ) (специалитет)'), ('RB', 'Бурение нефтяных и газовых скважин (РБ)'), ('OS', 'Эксплуатация и обслуживание объектов добычи нефти (РН)'), ('DG', 'Эксплуатация и обслуживание объектов добычи газа, газоконденсата и подземных хранилищ (РГ)'), ('TS', 'Сооружение и ремонт газонефтепроводов и газонефтехранилищ (ТС)'), ('TP', 'Эксплуатация и обслуживание объектов транспорта и хранения нефти, газа и продуктов переработки (ТП)'), ('RT', 'Технология бурения нефтяных и газовых скважин на суше и море (РТ) (специалитет)'), ('RS', 'Разработка и эксплуатация нефтяных и газовых месторождений (РС) (специалитет)')], max_length=200, null=True)),
                ('economic_major_choice_first', models.CharField(blank=True, choices=[('EE', 'Экономика и проекты устойчивого развития энергетики (ЭЭ)'), ('EM', 'Управление бизнесом в энергетике (ЭМ)')], max_length=200, null=True)),
                ('economic_major_choice_second', models.CharField(blank=True, choices=[('EE', 'Экономика и проекты устойчивого развития энергетики (ЭЭ)'), ('EM', 'Управление бизнесом в энергетике (ЭМ)')], max_length=200, null=True)),
                ('first_confirm', models.BooleanField()),
                ('second_confirm', models.BooleanField()),
            ],
        ),
    ]
