# Generated by Django 4.2.1 on 2023-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomodel',
            name='copy_graduation_certificate',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='copy_passport',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='image_three_to_four',
            field=models.FileField(upload_to='files'),
        ),
    ]
