# Generated by Django 4.2.1 on 2023-06-01 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_maininfomodel_copy_graduation_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomodel',
            name='copy_graduation_certificate',
            field=models.FileField(upload_to='files/gr_certificates', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='copy_passport',
            field=models.FileField(upload_to='files/passports', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='image_three_to_four',
            field=models.FileField(upload_to='files/three_to_four', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
