# Generated by Django 4.2.1 on 2023-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_maininfomodel_copy_graduation_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomodel',
            name='major_choice',
            field=models.CharField(choices=[('Technic', 'Техническое направление'), ('Economic', 'Экономическое направление')], default='Technic', max_length=200),
        ),
    ]
