# Generated by Django 4.2.1 on 2023-06-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_maininfomodel_major_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomodel',
            name='graduation_place',
            field=models.CharField(choices=[('None', 'Choose somthing'), ('School', 'Школа'), ('College', 'Колледж'), ('Lyceum', 'Лицей')], max_length=20),
        ),
    ]
